CREATE TABLE Applicants (
  Id UNIQUEIDENTIFIER NOT NULL DEFAULT NewSequentialId(),
  CONSTRAINT [PK_Applicants] PRIMARY KEY CLUSTERED (Id ASC),
  RowVersion ROWVERSION,

  FirstName NVARCHAR(500) NOT NULL,
  LastName NVARCHAR(500) NOT NULL,
  Email NVARCHAR(500) NOT NULL,
  Essay NVARCHAR(MAX) NULL
)
